// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Cancel(arg1:string,arg2:string):Promise<void>;

export function Do(arg1:string,arg2:string):Promise<void>;

export function GetCPU():Promise<string>;

export function GetCPUCores():Promise<number>;

export function GetCPUMHz():Promise<number>;

export function GetItemGroups():Promise<Array<main.ItemGroup>>;

export function GetKernelVersion():Promise<string>;

export function GetOSName():Promise<string>;

export function GetPhyMem():Promise<number>;

export function GetStatus(arg1:string,arg2:string):Promise<boolean>;

export function GetUserName():Promise<string>;

export function GetVersion():Promise<string>;

export function GetVirMem():Promise<number>;
