// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1, arg2) {
  return window['go']['main']['App']['Cancel'](arg1, arg2);
}

export function Do(arg1, arg2) {
  return window['go']['main']['App']['Do'](arg1, arg2);
}

export function GetCPU() {
  return window['go']['main']['App']['GetCPU']();
}

export function GetCPUCores() {
  return window['go']['main']['App']['GetCPUCores']();
}

export function GetCPUMHz() {
  return window['go']['main']['App']['GetCPUMHz']();
}

export function GetItemGroups() {
  return window['go']['main']['App']['GetItemGroups']();
}

export function GetKernelVersion() {
  return window['go']['main']['App']['GetKernelVersion']();
}

export function GetOSName() {
  return window['go']['main']['App']['GetOSName']();
}

export function GetPhyMem() {
  return window['go']['main']['App']['GetPhyMem']();
}

export function GetStatus(arg1, arg2) {
  return window['go']['main']['App']['GetStatus'](arg1, arg2);
}

export function GetUserName() {
  return window['go']['main']['App']['GetUserName']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetVirMem() {
  return window['go']['main']['App']['GetVirMem']();
}
