// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPU():Promise<string>;

export function GetCPUCores():Promise<number>;

export function GetCPUMHz():Promise<number>;

export function GetKernelVersion():Promise<string>;

export function GetOSName():Promise<string>;

export function GetPhyMem():Promise<number>;

export function GetUserName():Promise<string>;

export function GetVersion():Promise<string>;

export function GetVirMem():Promise<number>;
